### ISSUE TITLE
new, more straightforward format

### ISSUE THREAD

**Issue by derhuerst** [juliuste/vbb-change-positions#8]
Currently, specifying change positions is a pain. While CSV is very low-barrier, it might be worth using [ndjson](http://ndjson.org) because it nicely handles nested data. I see having a helper tool as a requirement though, to make sure the barrier to contribute doesn't increase (and most likely decreases).

**Comment by sebkur** [comment]
I have been experimenting with a different, XML-based file format for defining this kind of data more conveniently.
Here's an [an overview](https://github.com/OpenMetroMaps/OpenMetroMaps#efficient-changing-and-other-station-data). More links: [file spec](https://github.com/OpenMetroMaps/OpenMetroMaps/blob/master/spec-change-format.md), [example data file](https://github.com/OpenMetroMaps/OpenMetroMaps/blob/master/example-data/example-changes.xml). The files from [OpenMetroMaps/berlin-change](https://github.com/OpenMetroMaps/berlin-change) are also stored in this format now.

I also implemented conversion code from my XML-based format to the CSV format:
See classes [TestConvertChangeModelBerlin](https://github.com/OpenMetroMaps/OpenMetroMaps/blob/master/java/change-model-csv-export/src/test/java/org/openmetromaps/change/TestConvertChangeModelBerlin.java) and [ChangeModelToCsvExporter](https://github.com/OpenMetroMaps/OpenMetroMaps/blob/master/java/change-model-csv-export/src/main/java/org/openmetromaps/change/ChangeModelToCsvExporter.java) for details on that.

**Comment by derhuerst** [comment]
I agree that the current CSV format is not convenient, but I'd say XML isn't the most straightforward format. Also, the argument for CSV was that less technical people can contribute, e.g. by using Excel.

https://github.com/OpenMetroMaps/OpenMetroMaps/blob/015ad078326fa0cf38a1a496aefbdb43a503f2f9/example-data/example-changes.xml#L3-L14 has no machine-readable version for the position on the platform.

https://github.com/OpenMetroMaps/OpenMetroMaps/blob/015ad078326fa0cf38a1a496aefbdb43a503f2f9/example-data/example-changes.xml#L16 – regarding regexes: I think it greatly increases the usability, but IMO it is better to have explicit information, rather than implicitly including all lines, as they might change in the future.

**Comment by sebkur** [comment]
yes, lines 3-14 are there to illustrate that there are sometimes more complex situations than the ones currently supported with the other storage mechanisms (especially multiple optimal positions on the platform). Providing some way to write it down for later refinement was the idea here

**Comment by sebkur** [comment]
I think eventually people shouldn't be contributing by interacting with the bare files anyways, but instead with some kind of UI

**Comment by derhuerst** [comment]
👍 Note that multiple entries are possible as well right now.

**Comment by sebkur** [comment]
Good point, didn't consider the possibility. It works in my current draft as well.

**Comment by juliuste** [comment]
I updated the format to `ndjson` and also allowed the grouping of `fromLines` / `toLines`, this reduces the complexity, to give an extreme example: `Westkreuz` has 14 data rows now instead of the 58 it used to have.

I'm open for further changes though, of course, this is just a "quick" proposal.
